# EDA dataset Amazon's Top 50 bestselling books from 2009 to 2019

In [179]:
# lod libraries
## Load libraries
import numpy as np
import pandas as pd
import chart_studio.plotly as py
import cufflinks as cf
import  seaborn as sns
import plotly.express as px
%matplotlib inline

#  to work offline in local computer
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
cf.go_offline()


In [300]:
# load data

df = pd.read_csv("bestsellers with categories.csv")
df.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

# EDA

In [181]:
# look at the shape of the data
df.shape

(550, 7)

In [182]:
# get info on the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
Name           550 non-null object
Author         550 non-null object
User Rating    550 non-null float64
Reviews        550 non-null int64
Price          550 non-null int64
Year           550 non-null int64
Genre          550 non-null object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


* We have numerical and categorical variables

In [183]:
# look if we have duplicated rows
df.duplicated().sum()

0

* No duplicated rows

In [191]:
df['Author'].duplicated().sum() 

302

* 302 similar authors names in the data

In [192]:
df['Name'].duplicated().sum()

199

* There is 199 identical books in the data

In [301]:
# look at authors and book names duplicated

# look at how many duplicate authors/books names we have in the list?

def duplicate_cols(col_name):
    for c in col_name:
        if df[c].duplicated().any() ==True:
            print(f'Columns {c} has {df[c].duplicated().sum()} duplicates.')
        else:
            print(f'Columns {c} has no duplicates')


cols = ['Name', 'Author']
duplicate_cols(cols)

Columns Name has 199 duplicates.
Columns Author has 302 duplicates.


In [303]:
# Check if spelling errors in Names and Authors names

for col in cols:
    print(f'Before {col}: {len(set(df[col]))} After {col}: {len(set(df[col].str.title().str.strip()))}')

Before Name: 351 After Name: 350
Before Author: 248 After Author: 248


* we hae typing errors in the names

In [304]:
# Fix typing error in the name

df.Name = df['Name'].str.title().str.strip()


In [308]:
# Check if the cahnge was included

for col in cols:
    print(f'Before {col}: {len(set(df[col]))} After {col}: {len(set(df[col].str.title().str.strip()))}')

Before Name: 350 After Name: 350
Before Author: 248 After Author: 248


In [309]:
# Check the same author name spelling errors

A = df['Author'].sort_values().unique()
A



array(['Abraham Verghese', 'Adam Gasiewski', 'Adam Mansbach', 'Adir Levy',
       'Admiral William H. McRaven', 'Adult Coloring Book Designs',
       'Alan Moore', 'Alex Michaelides', 'Alice Schertle', 'Allie Brosh',
       'American Psychiatric Association',
       'American Psychological Association', 'Amor Towles', 'Amy Ramos',
       'Amy Shields', 'Andy Weir', 'Angie Grace', 'Angie Thomas',
       'Ann Voskamp', 'Ann Whitford Paul', 'Anthony Bourdain',
       'Anthony Doerr', 'Atul Gawande', 'Audrey Niffenegger',
       'B. J. Novak', 'Bessel van der Kolk M.D.', 'Bill Martin Jr.',
       "Bill O'Reilly", 'Bill Simmons', 'Blue Star Coloring',
       'Bob Woodward', 'Brandon Stanton', 'Brené Brown',
       'Brian Kilmeade', 'Bruce Springsteen', 'Carol S. Dweck',
       'Celeste Ng', 'Charlaine Harris', 'Charles Duhigg',
       'Charles Krauthammer', 'Cheryl Strayed', 'Chip Gaines',
       'Chip Heath', 'Chris Cleave', 'Chris Kyle', 'Chrissy Teigen',
       'Christina Baker Kline', 

In [322]:
# Fix name of authors with too much space in it
# exple":

# Let's build a list of the most similar spellings
import difflib
for name in A:
    l = difflib.get_close_matches(name, A)  # Most closer name to name
    if len(l) >1:
        print(l)

['Alex Michaelides', 'Michael Lewis']
['American Psychiatric Association', 'American Psychological Association']
['American Psychological Association', 'American Psychiatric Association']
['Angie Grace', 'Angie Thomas']
['Angie Thomas', 'Angie Grace']
['Anthony Bourdain', 'Anthony Doerr']
['Anthony Doerr', 'Anthony Bourdain']
['Brené Brown', 'Dan Brown']
['Charles Duhigg', 'Charles Krauthammer']
['Charles Krauthammer', 'Charles Duhigg']
['Cheryl Strayed', 'Sheryl Sandberg']
['Chris Cleave', 'Chris Kyle', 'Chrissy Teigen']
['Chris Kyle', 'Chris Cleave', 'Crispin Boyer']
['Chrissy Teigen', 'Chris Cleave']
['Christina Baker Kline', 'Christopher Paolini']
['Christopher Paolini', 'Christina Baker Kline']
['Craig Smith', 'JJ Smith']
['Crispin Boyer', 'Chris Kyle']
['Dan Brown', 'Daniel James Brown', 'Brené Brown']
['Daniel H. Pink', 'Daniel Lipkowitz']
['Daniel James Brown', 'Dan Brown']
['Daniel Kahneman', 'Daniel James Brown']
['Daniel Lipkowitz', 'Daniel H. Pink']
['David Goggins', 'Dav

In [323]:
# I saw only those two names that are similar
#.... This part need to be more automate so that we do not have to look manually at names

# ['George R. R. Martin', 'George R.R. Martin']
# ['J. K. Rowling', 'J.K. Rowling']

# Replace those name by the same name
# Replace the names of the authors with the correct ones
df = df.replace('George R. R. Martin', 'George R.R. Martin')
df = df.replace('J. K. Rowling', 'J.K. Rowling')


In [326]:
# Take the data with same authors/books name

df_SameAuthor = df.loc[df['Author'].duplicated()]
# df_SameName = df.loc[df['N'].duplicated()]
df_SameAuthor.shape

(304, 7)

In [343]:
# Count the number of each book in the data

count_books = dict()

for k in list(df['Author']):
    count_books[k] = count_books.get(k, 0) + 1
# print(count_books)

# Which is the Author with more books in the data?
# list of 5 Authors

lst = list()
for key, val in count_books.items():
    newtup = (val, key)
    lst.append(newtup)

# sort the list descendent way
lst = sorted(lst, reverse=True)

# Take the 5 most popular books Authors in the data
for val, key in lst[:5]:
    print(key, val)
    

Jeff Kinney 12
Suzanne Collins 11
Rick Riordan 11
Gary Chapman 11
American Psychological Association 10


* The Author with the most books is "Jeff Kinney"

In [347]:
# Extract all the books writen by this author
df_Jeff_Kinney = df.loc[df['Author'] =='Jeff Kinney']
df_Jeff_Kinney 

Name       Author  \
42          Cabin Fever (Diary Of A Wimpy Kid, Book 6)  Jeff Kinney   
71             Diary Of A Wimpy Kid: Hard Luck, Book 8  Jeff Kinney   
72       Diary Of A Wimpy Kid: The Last Straw (Book 3)  Jeff Kinney   
73                 Diary Of A Wimpy Kid: The Long Haul  Jeff Kinney   
80   Dog Days (Diary Of A Wimpy Kid, Book 4) (Volum...  Jeff Kinney   
88              Double Down (Diary Of A Wimpy Kid #11)  Jeff Kinney   
253              Old School (Diary Of A Wimpy Kid #10)  Jeff Kinney   
381                                        The Getaway  Jeff Kinney   
435        The Meltdown (Diary Of A Wimpy Kid Book 13)  Jeff Kinney   
468     The Third Wheel (Diary Of A Wimpy Kid, Book 7)  Jeff Kinney   
474      The Ugly Truth (Diary Of A Wimpy Kid, Book 5)  Jeff Kinney   
545       Wrecking Ball (Diary Of A Wimpy Kid Book 14)  Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
42           4.8     4505      0  2011  Fiction  
71           4.8     6812      0  2013  Fiction  
72           4.8     3837     15  2009  Fiction  
73           4.8     6540     22  2014  Fiction  
80           4.8     3181     12  2009  Fiction  
88           4.8     5118     20  2016  Fiction  
253          4.8     6169      7  2015  Fiction  
381          4.8     5836      0  2017  Fiction  
435          4.8     5898      8  2018  Fiction  
468          4.7     6377      7  2012  Fiction  
474          4.8     3796     12  2010  Fiction  
545          4.9     9413      8  2019  Fiction

* We notice that 'Jeff mKinney' write only 'Fiction' books, and have very good User rating from 4.7
* He has been writing since 2009, and have wrote a book every year.
* His books are really not expenive

In [358]:
# The Authors with the most expensive books

df_bestsale_author = df.loc[df['Price'] == df['Price'].max()]
df_bestsale_author 

Name  \
69  Diagnostic And Statistical Manual Of Mental Di...   
70  Diagnostic And Statistical Manual Of Mental Di...   

                              Author  User Rating  Reviews  Price  Year  \
69  American Psychiatric Association          4.5     6679    105  2013   
70  American Psychiatric Association          4.5     6679    105  2014   

          Genre  
69  Non Fiction  
70  Non Fiction

*  For two years consecutive, the Author ' American Psychiatric Association' have sale his book very high price.

In [359]:
# The Authors with the less expensive book

df_cheapsale_author = df.loc[df['Price'] == df['Price'].min()]
df_cheapsale_author 

Name  \
42          Cabin Fever (Diary Of A Wimpy Kid, Book 6)   
71             Diary Of A Wimpy Kid: Hard Luck, Book 8   
116                        Frozen (Little Golden Book)   
193                               Journey To The Ice P   
219                                  Little Blue Truck   
358              The Constitution Of The United States   
381                                        The Getaway   
461  The Short Second Life Of Bree Tanner: An Eclip...   
505                              To Kill A Mockingbird   
506                              To Kill A Mockingbird   
507                              To Kill A Mockingbird   
508                              To Kill A Mockingbird   

                               Author  User Rating  Reviews  Price  Year  \
42                        Jeff Kinney          4.8     4505      0  2011   
71                        Jeff Kinney          4.8     6812      0  2013   
116                         RH Disney          4.7     3642      0  2014   
193                         RH Disney          4.6      978      0  2014   
219                    Alice Schertle          4.9     1884      0  2014   
358  Delegates of the Constitutional
          4.8     2774      0  2016   
381                       Jeff Kinney          4.8     5836      0  2017   
461                   Stephenie Meyer          4.6     2122      0  2010   
505                        Harper Lee          4.8    26234      0  2013   
506                        Harper Lee          4.8    26234      0  2014   
507                        Harper Lee          4.8    26234      0  2015   
508                        Harper Lee          4.8    26234      0  2016   

           Genre  
42       Fiction  
71       Fiction  
116      Fiction  
193      Fiction  
219      Fiction  
358  Non Fiction  
381      Fiction  
461      Fiction  
505      Fiction  
506      Fiction  
507      Fiction  
508      Fiction

In [434]:
fig = px.scatter(df_cheapsale_author,
          x ='User Rating', 
          y = 'Author', 
          color ='Genre', 
          size= 'User Rating', 
           hover_data=['User Rating'],
           text='Year',
          )

fig.update_traces(textposition='top center')

fig.update_layout(title_text='Books with lower price')

fig.show()


In [366]:
print(df_cheapsale_author.Year.max(), df_cheapsale_author.Year.min())

2017 2010


In [375]:
df_cheapsale_author['User Rating'].max()

4.9

* The author Jeff Kinney have user rating progressing positively from 2010 to 2017
* Harper Lee have also a very good progressing User Rating
* Alice Schertle , Delegates of the Constitutional and Stephenie Meyer have books in 2010,2014 and 2016 with lower rate despide the lower price of the book.
*  RH Disney has a constant User rating of his book 

In [32]:
# Create a stacked bar plot

px.bar(df,
       x = 'Year',
      y= 'Price',
      color ='Genre',
      title ='Price for each book genre on Each Year',
      labels ={'x': 'Prices', 'y': 'Years'})


* We clearly notice that the genre ' Non fiction" is more expensive than the genre 'Fiction'.
* We notice an price increase of the two genre until 2014 where the prices start to drop 
* in 2015, there is a massive drop of the Fiction genre of book ( the price is at his lower cost.

* The author whose book is/(has been) the more expensive ia 'E.L. James' in 2012, genre 'Fiction'

* The cheapest book was '10-Day Green Smoothie Cleanse' a non Fiction book written by 'JJ Smith'

In [436]:
# Look at reviews per book genre
fig = px.bar(df,
             y ='Reviews', 
             x ='Genre',
#              text ='',
             color ='Genre',
             title ='Reviews of books per genre'
            )
fig

* The 'Fiction' genre has better reviews than the on fiction type of book 

In [101]:
# Look in 2015 only where the price were the lowest for the two genres of book
df_2015 = df.loc[df['Year']==2015]


fig = px.bar(df_2015,
             y ='Reviews', 
             x ='Author',
             text ='User Rating',
#              barmode ='group',
             color ='Genre'
            )
# we add update the figure
fig.update_traces(texttemplate ='%{text:.2s}', textposition = 'outside')
fig.update_layout(uniformtext_minsize =12)
# rotate labels x to 45 degree
fig.update_layout(xaxis_tickangle =-45)

fig

* In 2015, the 'Fiction' books have the best reviews  but not the more expensive price.
*  The high number of reviews does not mean best user rating. 

In [61]:
df_2015_best_price = df_2015.loc[df_2015['Price'] == df_2015['Price'].max()]
df_2015_best_price

Name  \
277  Publication Manual of the American Psychologic...   

                                 Author  User Rating  Reviews  Price  Year  \
277  American Psychological Association          4.5     8580     46  2015   

           Genre  
277  Non Fiction

In [139]:
px.pie(df_2015, 
       values ='Reviews', 
       names ='Genre',
       title ='Reviews percentages per book type in 2015',
      color_discrete_sequence = px.colors.sequential.RdBu
       )


In [160]:
px.histogram(df_2015, 
            x ='User Rating',
            color ='Genre',
            barmode='stack')


* High user rate for Fiction book in 2015

In [168]:
df_Rating_best = df.loc[df['User Rating'] >= 4.9]
len(df_Rating_best['User Rating'])

# only 52 books have 4.9 and above rating score



52

In [173]:
# plot the best rating books
px.bar(df_Rating_best,
       x = 'Year', 
       y = 'Reviews',
        color='Genre',
       barmode='group'
      )

In [451]:
# Authors with the best User Rating
df_bestrate = df.loc[df['User Rating'] == df['User Rating'].max()]
df_bestrate = df_bestrate[['Author', 'User Rating']]


df_bestrate['Author'].unique()
# # Take only unique author names mand have a list of authors with best user rating 
# drop duplicated Author names
df_bestrate = df_bestrate.drop_duplicates(subset = 'Author', keep = 'first')
df_bestrate

Author  User Rating
40         Bill Martin Jr.          4.9
81              Dav Pilkey          4.9
146   Sherri Duskey Rinker          4.9
151     Lin-Manuel Miranda          4.9
153           J.K. Rowling          4.9
174        Brandon Stanton          4.9
187            Sarah Young          4.9
207             Jill Twiss          4.9
219         Alice Schertle          4.9
244             Pete Souza          4.9
245              Dr. Seuss          4.9
288          Rush Limbaugh          4.9
303         Nathan W. Pyle          4.9
420         Patrick Thorpe          4.9
431            Chip Gaines          4.9
476             Eric Carle          4.9
486  Emily Winfield Martin          4.9
521          Mark R. Levin          4.9
545            Jeff Kinney          4.9

### Conclusion:

*  The following authors have highest rating: ['Bill Martin Jr.',  'Dav Pilkey',  'Sherri Duskey Rinker',  'Lin-Manuel Miranda',  'J.K. Rowling',  'Brandon Stanton',
 'Sarah Young',  'Jill Twiss',  'Alice Schertle',  'Pete Souza',  'Dr. Seuss',  'Rush Limbaugh',  'Nathan W. Pyle',  'Patrick Thorpe',  'Chip Gaines',  'Eric Carle',
 'Emily Winfield Martin',  'Mark R. Levin',  'Jeff Kinney'].  They all have User Rating of 4.9.
 
 
* The 5 top best sellers authors are : 
 Jeff Kinney: 12
Suzanne Collins: 11
Rick Riordan: 11
Gary Chapman: 11
American Psychological Association: 10


* Author that write   'Non-fiction' book Genre is more likely to become a bestseller. 


  
    